// <auto-generated />
using System;
using CriticsDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CriticsDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CriticsDB.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<int>("AccessFailedCount").HasColumnType("INTEGER");
                b.Property<string>("AvatarUrl").HasColumnType("TEXT");
                b.Property<string>("Bio").HasColumnType("TEXT");
                b.Property<string>("ConcurrencyStamp").HasColumnType("TEXT");
                b.Property<string>("DisplayName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<bool>("EmailConfirmed").HasColumnType("INTEGER");
                b.Property<DateTime>("JoinedAt").HasColumnType("TEXT");
                b.Property<bool>("LockoutEnabled").HasColumnType("INTEGER");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("TEXT");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").HasColumnType("TEXT");
                b.Property<string>("PhoneNumber").HasColumnType("TEXT");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("INTEGER");
                b.Property<string>("SecurityStamp").HasColumnType("TEXT");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("INTEGER");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("AspNetUsers", (string)null);
            });

            modelBuilder.Entity("CriticsDB.Models.Movie", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Director").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Genre").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("PosterUrl").HasColumnType("TEXT");
                b.Property<DateTime>("ReleaseDate").HasColumnType("TEXT");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("TrailerUrl").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Movies");
            });

            modelBuilder.Entity("CriticsDB.Models.Rating", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<int>("MovieId").HasColumnType("INTEGER");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.Property<int>("Value").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("MovieId");
                b.HasIndex("UserId", "MovieId").IsUnique();
                b.ToTable("Ratings");
            });

            modelBuilder.Entity("CriticsDB.Models.Review", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Comment").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<int>("MovieId").HasColumnType("INTEGER");
                b.Property<int>("Rating").HasColumnType("INTEGER");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("MovieId");
                b.HasIndex("UserId", "MovieId").IsUnique();
                b.ToTable("Reviews");
            });

            modelBuilder.Entity("CriticsDB.Models.ReviewLike", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<bool>("IsLike").HasColumnType("INTEGER");
                b.Property<int>("ReviewId").HasColumnType("INTEGER");
                b.Property<string>("UserId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ReviewId");
                b.HasIndex("UserId", "ReviewId").IsUnique();
                b.ToTable("ReviewLikes");
            });
#pragma warning restore 612, 618
        }
    }
}
